[package]
name = "neolink"
description = "A standards-compliant bridge to Reolink IP cameras"
version = "0.5.1"
authors = ["George Hilliard <thirtythreeforty@gmail.com>", "Andrew King <sheepchaan@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "crates/*",
]

[dependencies]
neolink_core = { path = "crates/core", version = "0.5.1" }
aes = "0.6"
cfb-mode = "0.6"
cookie-factory = "0.3"
crossbeam = "0.8"
crossbeam-channel = "0.5.1"
err-derive = "0.2"
env_logger = "*"
gstreamer = "0.19.0"
gstreamer-app = "0.19.0"
gstreamer-rtsp = "0.19.0"
gstreamer-rtsp-server = { version = "0.19.0", features = ["v1_16"]}
lazy_static = "1.4"
log = { version = "0.4" }
itertools = "0.9"
md5 = "0.7"
nom = "6.1.2"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
socket2 = "0.3"
structopt = "0.3"
time = "0.2"
toml = "0.5"
yaserde = "0.3.16"
yaserde_derive = "0.3.16"
xml-rs = "0.8"
validator = "0.10"
validator_derive = "0.10"
byte-slice-cast = "1.0.0"
rumqttc = "0.8.0"
tokio = { version = "1.0", features = ["rt", "macros", "io-util"] }
anyhow = "1.0.42"
async-trait = "0.1.64"
