name: Style

on: [push, pull_request]

jobs:
  check_clippy:
    name: Clippy
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: apt install gstreamer
      run: |
        sudo apt update
        sudo apt install -y aptitude
        sudo aptitude install -y libgstrtspserver-1.0-dev libgstreamer1.0-dev libgtk2.0-dev
    - name: Install nightly rust
      run: |
          rustup toolchain install nightly --component cargo
          rustup override set nightly
    - name: Run clippy manually
      run: cargo +nightly clippy --workspace --all-targets --all-features

  check_fmt:
    name: Rust-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nightly rust
      run: |
          rustup toolchain install nightly --component rustfmt
          rustup override set nightly
    - name: rustfmt
      run: |
        cargo +nightly fmt --all -- --check

  check_lua:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        files: 'dissector/baichuan.lua'
        args: --globals Dissector Proto ProtoField base ByteArray DESEGMENT_ONE_MORE_SEGMENT DissectorTable
